package com.example.volumen.utils

const val VERSION_NAME = "Versión"
const val ERROR_RUT_1 = "RUT requerido"
const val ERROR_RUT_2 = "RUT inválido"

const val URL_BASE = "https://192.168.1.1/api/"
const val URL_PORTICO = "/api/getStatus"
const val URL_VOLUMEN = "/api/getVolumen"
const val URL_IMAGEN = "/api/download_file/"

const val KEY_SCANDIT = "ASlgvi91DhXYEzgsxAQvaCUMxci2CkamSgFqafNCmNIxfcjMMGoFlLVtxNFzTfFOm1GcsddNvDIyEsIFaX7wKTFRjiQbfMxNRyRut5dlFtK4ZJPqJFgusGlFVTnMPIwbyg+K85AGsN7jQuPWi6vjyx4r4xLZRhRan8B/h1dreRZ+eJNwrEKwRExT0ssnrap2iFuCXQtAASjY1zXaTaVE4XgxzxXGpDqIwqLvYfWaDQ9WAza8BYsf4tgdWQaLxx9yIz7Qq7hEOVCw4yNtwp4faqYZCyjDz+uIgrxqzZiqY3pF35BG8yFvwis6t1xQi+AsNf6B6mDCeVBnHKnU06g5oVU4+uN2Q2Mk5tZGpqZRkTU2q9/UD21jnkw66t387wwyoJX7ehWhT8PPO9nmtmKkj71Hry06yfCpD/8T+SRUBmyh4azmZW9bb43GHgCcbY+RYWnMwZOSIBaOlVsiMTSPFF4oLbP3wcjouFm/QbiOP4FxfaE5uNQKAZk5rvbuctc6sugFb/vhCbnKHIgEezn72+AFG5/YiOduYaQDQCTwuf252KmaWTsVpsSqDOXkSjVgTYtQxsJWAyx4qIu5ACvcds8oOxqtu7jDBkxzr2W7n+jgWcAWKZcv+oeUj8Nc2OrWmNwNv9uOuuEM0raFBhkje1mw6eSMmkyRySCPRhmhgpXwTmkq2wLmtYdafv2auEJ0tY2x5FQyhHEQop6YIH7vYGosrtDXjfEL9xajuCKmanRdSf+uLOHD5bb0AxxwGs4LYaIB25umsTvXDxTiNV6oUBaMlCL2ACKBBm4OeUiHHGuLbzG/y/Na+lTk9g=="